# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12.1
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.1

    - name: Install Poetry
      run: pipx install poetry==1.7.1

    - name: Install dependencies
      run: make install

    - name: Lint the code
      run: make lint

    - name: Format the code
      run: make format

    - name: Check the code
      run: make check
